In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
wbcd=pd.read_csv("D:\DATA SCIENCE\DATA SETS\KNN\wbcd.csv")

In [4]:
wbcd

id diagnosis  radius_mean  texture_mean  perimeter_mean  \
0     87139402         B        12.32         12.39           78.85   
1      8910251         B        10.60         18.95           69.28   
2       905520         B        11.04         16.83           70.92   
3       868871         B        11.28         13.39           73.00   
4      9012568         B        15.19         13.21           97.65   
..         ...       ...          ...           ...             ...   
564  911320502         B        13.17         18.22           84.28   
565     898677         B        10.26         14.71           66.20   
566     873885         M        15.28         22.41           98.92   
567     911201         B        14.53         13.98           93.86   
568    9012795         M        21.37         15.10          141.30   

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
0        464.1          0.10280           0.06981         0.03987   
1        346.4          0.09688           0.11470         0.06387   
2        373.2          0.10770           0.07804         0.03046   
3        384.8          0.11640           0.11360         0.04635   
4        711.8          0.07963           0.06934         0.03393   
..         ...              ...               ...             ...   
564      537.3          0.07466           0.05994         0.04859   
565      321.6          0.09882           0.09159         0.03581   
566      710.6          0.09057           0.10520         0.05375   
567      644.2          0.10990           0.09242         0.06895   
568     1386.0          0.10010           0.15150         0.19320   

     points_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0        0.03700  ...         13.50          15.64            86.97   
1        0.02642  ...         11.88          22.94            78.28   
2        0.02480  ...         12.41          26.44            79.93   
3        0.04796  ...         11.92          15.77            76.53   
4        0.02657  ...         16.20          15.73           104.50   
..           ...  ...           ...            ...              ...   
564      0.02870  ...         14.90          23.89            95.10   
565      0.02037  ...         10.88          19.48            70.89   
566      0.03263  ...         17.80          28.03           113.80   
567      0.06495  ...         15.80          16.93           103.10   
568      0.12550  ...         22.69          21.84           152.10   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0         549.1            0.1385             0.1266          0.12420   
1         424.8            0.1213             0.2515          0.19160   
2         471.4            0.1369             0.1482          0.10670   
3         434.0            0.1367             0.1822          0.08669   
4         819.1            0.1126             0.1737          0.13620   
..          ...               ...                ...              ...   
564       687.6            0.1282             0.1965          0.18760   
565       357.1            0.1360             0.1636          0.07162   
566       973.1            0.1301             0.3299          0.36300   
567       749.9            0.1347             0.1478          0.13730   
568      1535.0            0.1192             0.2840          0.40240   

     points_worst  symmetry_worst  dimension_worst  
0         0.09391          0.2827          0.06771  
1         0.07926          0.2940          0.07587  
2         0.07431          0.2998          0.07881  
3         0.08611          0.2102          0.06784  
4         0.08178          0.2487          0.06766  
..            ...             ...              ...  
564       0.10450          0.2235          0.06925  
565       0.04074          0.2434          0.08488  
566       0.12260          0.3175          0.09772  
567       0.10690          0.2606          0.07810  
568       0.19660

In [6]:
wbcd.head(1)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0  87139402         B        12.32         12.39           78.85      464.1   

   smoothness_mean  compactness_mean  concavity_mean  points_mean  ...  \
0           0.1028           0.06981         0.03987        0.037  ...   

   radius_worst  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0          13.5          15.64            86.97       549.1            0.1385   

   compactness_worst  concavity_worst  points_worst  symmetry_worst  \
0             0.1266           0.1242       0.09391          0.2827   

   dimension_worst  
0          0.06771  

[1 rows x 32 columns]

In [8]:
wbcd['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [10]:
freq=(pd.crosstab(index=wbcd['diagnosis'],columns="count"))

In [11]:
freq

col_0      count
diagnosis       
B            357
M            212

In [12]:
freq/freq.sum()

col_0         count
diagnosis          
B          0.627417
M          0.372583

In [13]:
del wbcd['id']

In [14]:
wbcd

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           B        12.32         12.39           78.85      464.1   
1           B        10.60         18.95           69.28      346.4   
2           B        11.04         16.83           70.92      373.2   
3           B        11.28         13.39           73.00      384.8   
4           B        15.19         13.21           97.65      711.8   
..        ...          ...           ...             ...        ...   
564         B        13.17         18.22           84.28      537.3   
565         B        10.26         14.71           66.20      321.6   
566         M        15.28         22.41           98.92      710.6   
567         B        14.53         13.98           93.86      644.2   
568         M        21.37         15.10          141.30     1386.0   

     smoothness_mean  compactness_mean  concavity_mean  points_mean  \
0            0.10280           0.06981         0.03987      0.03700   
1            0.09688           0.11470         0.06387      0.02642   
2            0.10770           0.07804         0.03046      0.02480   
3            0.11640           0.11360         0.04635      0.04796   
4            0.07963           0.06934         0.03393      0.02657   
..               ...               ...             ...          ...   
564          0.07466           0.05994         0.04859      0.02870   
565          0.09882           0.09159         0.03581      0.02037   
566          0.09057           0.10520         0.05375      0.03263   
567          0.10990           0.09242         0.06895      0.06495   
568          0.10010           0.15150         0.19320      0.12550   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.1959  ...         13.50          15.64            86.97   
1           0.1922  ...         11.88          22.94            78.28   
2           0.1714  ...         12.41          26.44            79.93   
3           0.1771  ...         11.92          15.77            76.53   
4           0.1721  ...         16.20          15.73           104.50   
..             ...  ...           ...            ...              ...   
564         0.1454  ...         14.90          23.89            95.10   
565         0.1633  ...         10.88          19.48            70.89   
566         0.1727  ...         17.80          28.03           113.80   
567         0.1650  ...         15.80          16.93           103.10   
568         0.1973  ...         22.69          21.84           152.10   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0         549.1            0.1385             0.1266          0.12420   
1         424.8            0.1213             0.2515          0.19160   
2         471.4            0.1369             0.1482          0.10670   
3         434.0            0.1367             0.1822          0.08669   
4         819.1            0.1126             0.1737          0.13620   
..          ...               ...                ...              ...   
564       687.6            0.1282             0.1965          0.18760   
565       357.1            0.1360             0.1636          0.07162   
566       973.1            0.1301             0.3299          0.36300   
567       749.9            0.1347             0.1478          0.13730   
568      1535.0            0.1192             0.2840          0.40240   

     points_worst  symmetry_worst  dimension_worst  
0         0.09391          0.2827          0.06771  
1         0.07926          0.2940          0.07587  
2         0.07431          0.2998          0.07881  
3         0.08611          0.2102          0.06784  
4         0.08178          0.2487          0.06766  
..            ...             ...              ...  
564       0.10450          0.2235          0.06925  
565       0.04074          0.2434          0.08488  
566       0.12260          0.3175          0.09772  
567       0.10

# assigning x and y values 

In [19]:
x=wbcd.iloc[:,1:].values
y=wbcd.iloc[:,0].values

In [20]:
y

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M',
       'M', 'M', 'M', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M',
       'M', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'M', 'M', 'M',
       'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'M',
       'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B',
       'B', 'M', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B

# scaling the input data

In [22]:
x=(x-x.min())/(x.max()-x.min())

In [23]:
x

array([[2.89609779e-03, 2.91255289e-03, 1.85354960e-02, ...,
        2.20756935e-05, 6.64551011e-05, 1.59167842e-05],
       [2.49177245e-03, 4.45463094e-03, 1.62858486e-02, ...,
        1.86318759e-05, 6.91114245e-05, 1.78349788e-05],
       [2.59520451e-03, 3.95627645e-03, 1.66713681e-02, ...,
        1.74682652e-05, 7.04748472e-05, 1.85260931e-05],
       ...,
       [3.59191349e-03, 5.26798307e-03, 2.32534086e-02, ...,
        2.88199342e-05, 7.46356370e-05, 2.29713211e-05],
       [3.41560884e-03, 3.28631876e-03, 2.20639398e-02, ...,
        2.51292901e-05, 6.12599906e-05, 1.83591913e-05],
       [5.02350729e-03, 3.54960038e-03, 3.32157969e-02, ...,
        4.62153268e-05, 6.41748942e-05, 2.03714151e-05]])

# splitting the data

In [24]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80)

# applying knn algorithm

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [102]:
classifier1=KNeighborsClassifier(n_neighbors=7)

In [103]:
classifier1.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [104]:
#prediicting the model

y_pred=classifier1.predict(x_test)

In [105]:
y_pred

array(['B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M',
       'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'B',
       'M', 'M', 'B', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B'], dtype=object)

In [106]:
# confusion matrix knn

from sklearn.metrics import confusion_matrix

In [107]:
print(confusion_matrix(y_test,y_pred))

[[71  1]
 [11 31]]


In [108]:
# Accuracy score

from sklearn.metrics import accuracy_score

In [109]:
Accuracy_score=accuracy_score(y_test,y_pred)

In [110]:
Accuracy_score

0.8947368421052632

# applying naive bayes classifier algorithm

In [114]:
from sklearn.naive_bayes import GaussianNB

In [115]:
classifier2=GaussianNB()

In [116]:
classifier2.fit(x_train,y_train)

GaussianNB()

In [124]:
#predicting the model
y_pred2=classifier2.predict(x_test)

In [125]:
y_pred2

array(['B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M',
       'B', 'M', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'M',
       'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'M', 'M', 'B', 'M',
       'M', 'B', 'B', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B'], dtype='<U1')

In [129]:
#confusion matrix of naive bayes classifier

confusion_matrix(y_test,y_pred2)

array([[70,  2],
       [ 6, 36]], dtype=int64)

In [128]:
#accuracy score of naive bayes clasifier

print(accuracy_score(y_test,y_pred2))

0.9298245614035088


# support vector machine(svm)

In [132]:
from sklearn.svm import SVC

In [165]:
classifier3=SVC(kernel='rbf')

In [166]:
classifier3.fit(x_train,y_train)

SVC()

In [167]:
#predicting the svm model
y_pred3=classifier3.predict(x_test)

In [168]:
y_pred3

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'M', 'M', 'B', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B'], dtype=object)

In [169]:
#confusion matrix
confusion_matrix(y_test,y_pred3)

array([[72,  0],
       [14, 28]], dtype=int64)

In [170]:
#accuracy score
print(accuracy_score(y_test,y_pred3))

0.8771929824561403


# decision tree

In [171]:
from sklearn.tree import DecisionTreeClassifier

In [172]:
classifier4=DecisionTreeClassifier(criterion='entropy')

In [173]:
classifier4.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [174]:
#predicting the model
y_pred4=classifier4.predict(x_test)

In [175]:
#confusin matrix
confusion_matrix(y_test,y_pred4)

array([[70,  2],
       [ 5, 37]], dtype=int64)

In [176]:
#accuracy score
print(accuracy_score(y_test,y_pred4))

0.9385964912280702


# Random forest(ensemble)

In [177]:
from sklearn.ensemble import RandomForestClassifier

In [213]:
classifier5=RandomForestClassifier(n_estimators=20,criterion='entropy')

In [214]:
classifier5.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=20)

In [215]:
#predicting the model on testing data
y_pred5=classifier5.predict(x_test)

In [216]:
#confusion matrix
confusion_matrix(y_test,y_pred5)

array([[71,  1],
       [ 4, 38]], dtype=int64)

In [217]:
#Accuracy score
print(accuracy_score(y_test,y_pred5))

0.956140350877193


# XGboosting

In [235]:
from xgboost.sklearn import XGBClassifier

In [236]:
classifier6=XGBClassifier()

In [237]:
classifier6.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [238]:
#predicting the model on the data
y_pred6=classifier6.predict(x_test)

In [239]:
#confusion matrix
confusion_matrix(y_test,y_pred6)

array([[72,  0],
       [ 6, 36]], dtype=int64)

In [240]:
#Accuracy score
print(accuracy_score(y_test,y_pred6))

0.9473684210526315


In [ ]:
#from the above algorithms since the random forest has the highest accuracy, classifier5 is the final algorithm