In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [4]:
Diabetes=pd.read_csv("D:\DATA SCIENCE\DATA SETS\Decision trees and Random forest\Diabetes.csv")

In [5]:
Diabetes

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [8]:
Diabetes.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [11]:
#dividing the data into input and out put variables
x=Diabetes.iloc[:,0:8].values
y=Diabetes.iloc[:,8].values

In [12]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [13]:
#scaling the data
x=(x-x.min())/(x.max()-x.min())

In [14]:
x

array([[0.0070922 , 0.1749409 , 0.08510638, ..., 0.03971631, 0.00074113,
        0.05910165],
       [0.00118203, 0.10047281, 0.07801418, ..., 0.03144208, 0.00041489,
        0.03664303],
       [0.00945626, 0.21631206, 0.07565012, ..., 0.02754137, 0.00079433,
        0.03782506],
       ...,
       [0.00591017, 0.143026  , 0.08510638, ..., 0.03096927, 0.0002896 ,
        0.03546099],
       [0.00118203, 0.14893617, 0.07092199, ..., 0.0355792 , 0.00041253,
        0.05555556],
       [0.00118203, 0.10992908, 0.08274232, ..., 0.03593381, 0.00037234,
        0.02718676]])

In [16]:
#dividind the data into testing and training
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80)

# KNN classifier


In [20]:
from sklearn.neighbors import KNeighborsClassifier 

In [88]:
classifier1=KNeighborsClassifier(n_neighbors=20)

In [89]:
classifier1.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=20)

In [90]:
#predicting the model on testing data
y_pred1=classifier1.predict(x_test)

In [91]:
y_pred1

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
      dtype=int64)

In [92]:
#confusion matrix
confusion_matrix(y_pred1,y_test)

array([[88, 26],
       [17, 23]], dtype=int64)

In [93]:
#accuracy score
accuracy_score(y_pred1,y_test)

0.7207792207792207

# Naive bayes classifier

In [94]:
from sklearn.naive_bayes import GaussianNB

In [95]:
classifier2=GaussianNB()

In [96]:
classifier2.fit(x_train,y_train)

GaussianNB()

In [97]:
#predicting the model on testing data
y_pred2=classifier2.predict(x_test)

In [98]:
#confusion matrix
confusion_matrix(y_pred2,y_test)

array([[84, 22],
       [21, 27]], dtype=int64)

In [99]:
#accuracy score
accuracy_score(y_pred2,y_test)

0.7207792207792207

# svm

In [100]:
from sklearn.svm import SVC

In [121]:
classifier3=SVC(kernel='poly')

In [122]:
classifier3.fit(x_train,y_train)

SVC(kernel='poly')

In [123]:
#predicting the model on testing data
y_pred3=classifier3.predict(x_test)

In [124]:
#confusion matrix
confusion_matrix(y_pred3,y_test)

array([[90, 28],
       [15, 21]], dtype=int64)

In [125]:
#accuracy score
accuracy_score(y_pred3,y_test)

0.7207792207792207

# Decision tree

In [126]:
from sklearn.tree import DecisionTreeClassifier

In [127]:
classifier4=DecisionTreeClassifier(criterion='entropy')

In [128]:
classifier4.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [129]:
#predicting the model on testing data
y_pred4=classifier4.predict(x_test)

In [130]:
#confusion matrix
confusion_matrix(y_pred4,y_test)

array([[80, 14],
       [25, 35]], dtype=int64)

In [131]:
#accuracy score
accuracy_score(y_pred4,y_test)

0.7467532467532467

# Random forest

In [132]:
from sklearn.ensemble import RandomForestClassifier

In [163]:
classifier5=RandomForestClassifier(n_estimators=3,criterion='entropy')

In [164]:
classifier5.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [165]:
#predicting the model on testing data
y_pred5=classifier5.predict(x_test)

In [166]:
#confusion matrix
confusion_matrix(y_pred5,y_test)

array([[82, 17],
       [23, 32]], dtype=int64)

In [167]:
#accuracy score
accuracy_score(y_pred5,y_test)

0.7402597402597403

# xg boost

In [169]:
from xgboost.sklearn import XGBClassifier

In [170]:
classifier6=XGBClassifier()

In [171]:
classifier6.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [172]:
#predicting the model on testing data
y_pred6=classifier6.predict(x_test)

In [173]:
#confusion matrix
confusion_matrix(y_pred6,y_test)

array([[86, 21],
       [19, 28]], dtype=int64)

In [174]:
#accuracy score
accuracy_score(y_pred6,y_test)

0.7402597402597403

# logistic regression

In [180]:
from sklearn.linear_model import LogisticRegression

In [182]:
classifier7=LogisticRegression()
classifier7.fit(x_train,y_train)

LogisticRegression()

In [183]:
#predicting the model on testing data
y_pred7=classifier7.predict(x_test)

In [184]:
#confusion matrix
confusion_matrix(y_pred7,y_test)

array([[99, 46],
       [ 6,  3]], dtype=int64)

In [185]:
#accuracy score
accuracy_score(y_pred7,y_test)

0.6623376623376623

In [ ]:
#since the decision tree algorithm has the highest accuracy, use the classifier4 for predicting the diabetes